[package]
name = "knight"
version = "0.1.0"
authors = ["faineance <faineance@users.noreply.github.com>"]

[dependencies]
structopt = "0.1.0"
structopt-derive = "0.1.0"
log = "0.3"
loggerv = "0.6"
error-chain = "0.11.0"
petgraph = "0.4.11"

futures = "0.1"
tokio-core = "0.1"
tokio-process = "0.1.1"